### ISSUE TITLE
TagBot failed after adding DOCUMENTER_KEY in iml

### ISSUE THREAD

**Issue by navidcy** [JuliaRegistries/TagBot#160]
I noticed that my [docs](https://fourierflows.github.io/GeophysicalFlowsDocumentation/dev/) were not being deployed for new tags of [GeophysicalFlows.jl](https://github.com/FourierFlows/GeophysicalFlows.jl). Following @DilumAluthge's suggestion,  I've added `DOCUMENTER_KEY` in my `TagBot.yml` as described [in the docs](https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#GitHub-Actions). I deleted that latest release and tag (`v0.5.1`) and waited for TagBot to run again. However, next time I got this [error](https://github.com/FourierFlows/GeophysicalFlows.jl/runs/769776212?check_suite_focus=true):

```
2020-06-14T11:01:26.8901155Z ##[command]/usr/bin/docker run --name degraafctagbot1_2f1a31 --label 3888d3 --workdir /github/workspace --rm -e INPUT_TOKEN -e INPUT_SSH -e INPUT_REGISTRY -e INPUT_GITHUB -e INPUT_GITHUB_API -e INPUT_BRANCHES -e INPUT_DISPATCH -e INPUT_DISPATCH_DELAY -e INPUT_LOOKBACK -e INPUT_SSH_PASSWORD -e INPUT_GPG -e INPUT_GPG_PASSWORD -e INPUT_CHANGELOG -e INPUT_CHANGELOG_IGNORE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/GeophysicalFlows.jl/GeophysicalFlows.jl":"/github/workspace" degraafc/tagbot:1
2020-06-14T11:01:40.4074995Z Processing version v0.5.1 (66c0d7c64242c5740c851768a431539219aa6c59)
2020-06-14T11:01:40.4078809Z Generating changelog for version v0.5.1 (66c0d7c64242c5740c851768a431539219aa6c59)
2020-06-14T11:01:40.4102910Z ERROR: Permission to FourierFlows/GeophysicalFlows.jl.git denied to deploy key
2020-06-14T11:01:40.4103235Z fatal: Could not read from remote repository.
2020-06-14T11:01:40.4103379Z 
2020-06-14T11:01:40.4103631Z Please make sure you have the correct access rights
2020-06-14T11:01:40.4103878Z and the repository exists.
2020-06-14T11:01:40.4106069Z ##[error]TagBot experienced an unexpected internal failure
2020-06-14T11:01:40.4110865Z Traceback (most recent call last):
2020-06-14T11:01:40.4111205Z   File "/root/tagbot/action/__main__.py", line 78, in <module>
2020-06-14T11:01:40.4111471Z     repo.create_release(version, sha)
2020-06-14T11:01:40.4111725Z   File "/root/tagbot/action/repo.py", line 383, in create_release
2020-06-14T11:01:40.4111996Z     self._git.create_tag(version, sha, log)
2020-06-14T11:01:40.4112264Z   File "/root/tagbot/action/git.py", line 102, in create_tag
2020-06-14T11:01:40.4112525Z     self.command("push", "origin", version)
2020-06-14T11:01:40.4112799Z   File "/root/tagbot/action/git.py", line 64, in command
2020-06-14T11:01:40.4113594Z     raise Abort(f"Git command '{cmd}' failed")
2020-06-14T11:01:40.4114237Z tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_d9egrbrx push origin v0.5.1' failed
2020-06-14T11:01:40.4114417Z 
2020-06-14T11:01:40.4114739Z Response (200): {
2020-06-14T11:01:40.4114981Z   "status": "Submitted error report"
2020-06-14T11:01:40.4115223Z }
2020-06-14T11:01:40.6270221Z Cleaning up orphan processes
```

**Comment by navidcy** [comment]
Hm... I also noticed that the section "TagBot & tagged versions" in [Documenter.jl docs](https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#GitHub-Actions) **only appears** in the lates dev version. Should I be using `Documenter#master` to build docs?

**Comment by christopher-dG** [comment]
No, you don't need to be on master for this to work.

I've never seen this specific error message before, but my best guess is that your deploy key lacks write permissions (which also makes no sense seeing as you already have documentation deployed). I would recommend resetting your `DOCUMENTER_KEY` and seeing if the same error continues to occur.

**Comment by navidcy** [comment]
Thanks @christopher-dG. I did what you suggested but unfortunately I still get the [same error](https://github.com/FourierFlows/GeophysicalFlows.jl/runs/770622330?check_suite_focus=true).

I don't know if this will give a hint of why this happens, but note that I'm deploying in a different repo: https://github.com/FourierFlows/GeophysicalFlowsDocumentation

**Comment by christopher-dG** [comment]
Oh well that's exactly why. Deploy keys are only useful in repositories in which you have added them. Have you added that same key to your documentation repo?

**Comment by navidcy** [comment]
I've only added the deploy key in the FourierFlows/GeophysicalFlowsDocumentation repo and the secret key in the FourierFlows/GeophysicalFlows.jl

Isn't this what I'm supposed to do?

**Comment by christopher-dG** [comment]
You'll need to add the public key with write access to the source repo too.

**Comment by navidcy** [comment]
I get an error message from GitHub saying "Key is already in use" 🙄

**Comment by christopher-dG** [comment]
Ah, that sucks. In that case the easiest thing to do by far is to use a [personal access token](https://github.com/JuliaRegistries/TagBot#personal-access-tokens-pats) for TagBot.

**Comment by navidcy** [comment]
With what scope? Would `repo` be enough?

**Comment by christopher-dG** [comment]
Yeah it just needs repo.

**Comment by navidcy** [comment]
and my `TagBot.yml` should be:

```
name: TagBot
on:
  schedule:
    - cron: 0 * * * *
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.TAGBOT_PAT }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
```
?

Apparently I did something wrong because the Documentation build [fails now](https://github.com/FourierFlows/GeophysicalFlows.jl/runs/770680569?check_suite_focus=true)...

**Comment by christopher-dG** [comment]
That looks like a network failure on GitHub's end. But now that you have a PAT, you don't actually need the SSH key attached to TagBot. You can remove the `ssh` input.

**Comment by navidcy** [comment]
:(

Still I get the [error](https://github.com/FourierFlows/GeophysicalFlows.jl/runs/770699778?check_suite_focus=true):

```
Processing version v0.5.1 (66c0d7c64242c5740c851768a431539219aa6c59)
38 Generating changelog for version v0.5.1 (66c0d7c64242c5740c851768a431539219aa6c59)
39 Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
40 ERROR: Permission to FourierFlows/GeophysicalFlows.jl.git denied to deploy key
41 fatal: Could not read from remote repository.
42 
43 Please make sure you have the correct access rights
44 and the repository exists.
45 ##[error]TagBot experienced an unexpected internal failure
46 Traceback (most recent call last):
47   File "/root/tagbot/action/__main__.py", line 78, in <module>
48     repo.create_release(version, sha)
49   File "/root/tagbot/action/repo.py", line 383, in create_release
50     self._git.create_tag(version, sha, log)
51   File "/root/tagbot/action/git.py", line 102, in create_tag
52     self.command("push", "origin", version)
53   File "/root/tagbot/action/git.py", line 64, in command
54     raise Abort(f"Git command '{cmd}' failed")
55 tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_9p0imf6n push origin v0.5.1' failed
56 
57 Response (200): {
58   "status": "Submitted error report"
59 }
```

**Comment by christopher-dG** [comment]
> 40 ERROR: Permission to FourierFlows/GeophysicalFlows.jl.git denied to deploy key

This indicates to me that it's still trying to push with an SSH key (which is confirmed by the fact that your `TagBot.yml` still includes the `ssh` input). Sorry, I shouldn't have said "you can remove the `ssh` input", I should have gone with "REMOVE THE `ssh` INPUT NOW OR ELSE!!!" 😅

**Comment by navidcy** [comment]
Thanks!

This seems to [have done the job](https://fourierflows.github.io/GeophysicalFlowsDocumentation/v0.5.1/)!
