### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by alexriss** [JuliaRegistries/TagBot#222]
I am experiencing an issue with TagBot@v1. When trying to tag the new version of my package it gives me "Resource not accessible by integration" (full details below). Similar issues have been reported:
- https://discourse.julialang.org/t/tagbot-unexpected-internal-error/74680
- https://github.com/JuliaRegistries/TagBotErrorReports/issues/83

It worked well for the previous versions (and all my other packages) and I have not changed my TagBot.yml workflow since.

Thanks!

```
Processing version v0.3.0 (a21667c85995afa4415e0e[40](https://github.com/alexriss/SpmImageTycoon.jl/runs/5184011674?check_suite_focus=true#step:3:40)07fa2a094233c646)
Generating changelog for version v0.3.0 (a21667c85995afa4[41](https://github.com/alexriss/SpmImageTycoon.jl/runs/5184011674?check_suite_focus=true#step:3:41)5e0e4007fa2a09[42](https://github.com/alexriss/SpmImageTycoon.jl/runs/5184011674?check_suite_focus=true#step:3:42)33c646)
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 94, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 5[43](https://github.com/alexriss/SpmImageTycoon.jl/runs/5184011674?check_suite_focus=true#step:3:43), in create_release
    self._repo.create_git_ref(f"refs/tags/{version}", tag.sha)
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 969, in create_git_ref
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "[docs.github.com/rest/reference/git#create-a-reference](https://docs.github.com/rest/reference/git#create-a-reference)"}

```
```
Response (200): {
  "status": "Submitted error report"
}
```

**Comment by omus** [comment]
Failure also noticed here: https://github.com/JuliaIO/Suppressor.jl/runs/5251086604?check_suite_focus=true

**Comment by jd-lara** [comment]
@alexriss did you manage to fix this? I am getting the same as reported in #226

**Comment by alexriss** [comment]
@jd-lara No, I didn't. In the end I mad a manual tag/release.. The next tags/releases worked, though. So maybe it was something that I had in the release notes. for this particular one. I haven't found out what the problem was.
