### ISSUE TITLE
Unexpected internal failure

### ISSUE THREAD

**Issue by adrhill** [JuliaRegistries/TagBot#225]
In [this run](https://github.com/adrhill/ExplainabilityMethods.jl/actions/runs/2017563788/attempts/1) TagBot failed.

The TagBot Action was "successful" but shows "TagBot experienced an unexpected internal failure" as an annotation:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/20258504/159458366-488e1233-563a-4f83-909e-67a5d1b4bd6d.png">

The full output is:
<details>

```
Run JuliaRegistries/TagBot@v1
  with:
    token: ***
    registry: JuliaRegistries/General
    github: github.com
    github_api: api.github.com
    branches: false
    dispatch: false
    dispatch_delay: 5
    lookback: 3
    draft: false
    user: github-actions[bot]
    email: 41898282+github-actions[bot]@users.noreply.github.com
    changelog: ## {{ package }} {{ version }}
  
  {% if previous_release %}
  [Diff since {{ previous_release }}]({{ compare_url }})
  {% endif %}
  
  {% if custom %}
  {{ custom }}
  {% endif %}
  
  {% if issues %}
  **Closed issues:**
  {% for issue in issues %}
  - {{ issue.title }} (#{{ issue.number }})
  {% endfor %}
  {% endif %}
  
  {% if pulls %}
  **Merged pull requests:**
  {% for pull in pulls %}
  - {{ pull.title }} (#{{ pull.number }}) (@{{ pull.author.username }})
  {% endfor %}
  {% endif %}

/usr/bin/docker run --name ghcriojuliaregistriestagbot1141_e6b144 --label 29a95e --workdir /github/workspace --rm -e INPUT_TOKEN -e INPUT_SSH -e INPUT_REGISTRY -e INPUT_GITHUB -e INPUT_GITHUB_API -e INPUT_BRANCHES -e INPUT_DISPATCH -e INPUT_DISPATCH_DELAY -e INPUT_LOOKBACK -e INPUT_SSH_PASSWORD -e INPUT_GPG -e INPUT_GPG_PASSWORD -e INPUT_REGISTRY_SSH -e INPUT_DRAFT -e INPUT_USER -e INPUT_EMAIL -e INPUT_BRANCH -e INPUT_CHANGELOG -e INPUT_CHANGELOG_IGNORE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ExplainabilityMethods.jl/ExplainabilityMethods.jl":"/github/workspace" ghcr.io/juliaregistries/tagbot:1.14.1
Processing version v0.2.0 (715c5a8cd704ff56c6452ab2bb7349a6732cde87)
Generating changelog for version v0.2.0 (715c5a8cd704ff56c6452ab2bb7349a6732cde87)
Cloning into '/tmp/tagbot_repo_u8kolo9g'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
error: 1294 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 94, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 529, in create_release
    log = self._changelog.get(version, sha)
  File "/root/tagbot/action/changelog.py", line 193, in get
    data = self._collect_data(version, sha)
  File "/root/tagbot/action/changelog.py", line 168, in _collect_data
    end = self._repo._git.time_of_commit(sha) + timedelta(minutes=1)
  File "/root/tagbot/action/git.py", line 141, in time_of_commit
    date = self.command("show", "-s", "--format=%cI", sha, repo=repo)
  File "/root/tagbot/action/git.py", line 60, in command
    args.extend(["-C", repo or self._dir])
  File "/root/tagbot/action/git.py", line 35, in _dir
    self.command("clone", url, dest, repo=None)
  File "/root/tagbot/action/git.py", line 71, in command
    raise Abort(f"Git command '{cmd}' failed")
tagbot.action.Abort: Git command 'git clone ***github.com/adrhill/ExplainabilityMethods.jl /tmp/tagbot_repo_u8kolo9g' failed

Response (502): {
  "message": "Internal server error"
}
```

</details>

**Comment by adrhill** [comment]
Running TagBot locally, I get a very similar error:
<details>

```bash
➜  TagBot git:(master) ✗ poetry run python -m tagbot.local --github https://github.com/adrhill/ExplainabilityMethods.jl
Repo: adrhill/ExplainabilityMethods.jl
Version: v0.2.0
Token:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/funks/Developer/TagBot/tagbot/local/__main__.py", line 64, in <module>
    main()
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/tagbot-1qF_z0X3-py3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/tagbot-1qF_z0X3-py3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/tagbot-1qF_z0X3-py3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/tagbot-1qF_z0X3-py3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/funks/Developer/TagBot/tagbot/local/__main__.py", line 58, in main
    r.create_release(version, sha)
  File "/Users/funks/Developer/TagBot/tagbot/action/repo.py", line 529, in create_release
    log = self._changelog.get(version, sha)
  File "/Users/funks/Developer/TagBot/tagbot/action/changelog.py", line 193, in get
    data = self._collect_data(version, sha)
  File "/Users/funks/Developer/TagBot/tagbot/action/changelog.py", line 176, in _collect_data
    "custom": self._custom_release_notes(version),
  File "/Users/funks/Developer/TagBot/tagbot/action/changelog.py", line 109, in _custom_release_notes
    pr = self._repo._registry_pr(version)
  File "/Users/funks/Developer/TagBot/tagbot/action/repo.py", line 196, in _registry_pr
    for pr in prs:
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/tagbot-1qF_z0X3-py3.9/lib/python3.9/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/tagbot-1qF_z0X3-py3.9/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/tagbot-1qF_z0X3-py3.9/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/tagbot-1qF_z0X3-py3.9/lib/python3.9/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/tagbot-1qF_z0X3-py3.9/lib/python3.9/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}
```

</details>

**Comment by christopher-dG** [comment]
Any 5xx is just GitHub's own downtime (they had an outage yesterday).
