### ISSUE TITLE
GitHub returned a 5xx error code

### ISSUE THREAD

**Issue by henry2004y** [JuliaRegistries/TagBot#228]
I have been using TagBot successfully in the past. However, Since last week somehow I repeatly encountered a 5xx error

https://github.com/henry2004y/Vlasiator.jl/runs/6333415574?check_suite_focus=true

```
Warning: GitHub returned a 5xx error code
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 74, in <module>
    versions = repo.new_versions()
  File "/root/tagbot/action/repo.py", line 432, in new_versions
    return self._filter_map_versions(versions)
  File "/root/tagbot/action/repo.py", line 271, in _filter_map_versions
    expected = self._commit_sha_from_registry_pr(version, tree)
  File "/root/tagbot/action/repo.py", line 205, in _commit_sha_from_registry_pr
    pr = self._registry_pr(version)
  File "/root/tagbot/action/repo.py", line 196, in _registry_pr
    for pr in prs:
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}
```

I did not touch any parts related to TagBot on my side. What shall I do to fix this?

**Comment by christopher-dG** [comment]
[5xx](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses) means an error on github's server side, nothing to be done.
