### ISSUE TITLE
TomlDecodeError: Key name found without value

### ISSUE THREAD

**Issue by fonsp** [JuliaRegistries/TagBot#251]
My TagBot failed to create the tag after my version was merged into General. I re-ran manually a couple of times but I keep getting the same error. I ended up generating the release by hand.

Error log:

```
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 67, in <module>
    if not repo.is_registered():
  File "/root/tagbot/action/repo.py", line 396, in is_registered
    root = self._registry_path
  File "/root/tagbot/action/repo.py", line 147, in _registry_path
    registry = toml.loads(contents.decoded_content.decode())
  File "/usr/local/lib/python3.8/site-packages/toml/decoder.py", line 3[59](https://github.com/fonsp/Pluto.jl/actions/runs/3761657391/jobs/6393615936#step:3:60), in loads
    raise TomlDecodeError("Key name found without value."
toml.decoder.TomlDecodeError: Key name found without value. Reached end of file. (line 5[64](https://github.com/fonsp/Pluto.jl/actions/runs/3761657391/jobs/6393615936#step:3:65)4 column 27 char 512000)

Response (200): {
  "status": "Submitted error report"
}
```

Run: https://github.com/fonsp/Pluto.jl/actions/runs/3761657391/jobs/6393615936

**Comment by fonsp** [comment]
A previous run with the same version of TagBot (1.14.1) went succesful: https://github.com/fonsp/Pluto.jl/actions/runs/3642689753/jobs/6150076070 No settings have changed since.

**Comment by fonsp** [comment]
I am also surprised that this run shows as "succeeded" 🤔
