### ISSUE TITLE
TagBot not releasing new version: `github.GithubException.GithubException: 502 {"message": "Server Error"}`

### ISSUE THREAD

**Issue by singularitti** [JuliaRegistries/TagBot#254]
I have the following error message after registering my package in the "General" repo:

```python
Warning: GitHub returned a 5xx error code
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 74, in <module>
    versions = repo.new_versions()
  File "/root/tagbot/action/repo.py", line 432, in new_versions
    return self._filter_map_versions(versions)
  File "/root/tagbot/action/repo.py", line 271, in _filter_map_versions
    expected = self._commit_sha_from_registry_pr(version, tree)
  File "/root/tagbot/action/repo.py", line 205, in _commit_sha_from_registry_pr
    pr = self._registry_pr(version)
  File "/root/tagbot/action/repo.py", line 196, in _registry_pr
    for pr in prs:
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 3[40](https://github.com/MineralsCloud/MillerIndices.jl/actions/runs/3934543237/jobs/6729385975#step:3:41), in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}
```

See [this job](https://github.com/MineralsCloud/MillerIndices.jl/actions/runs/3934543237/jobs/6729385975).

And yet it tells me the job was successful.

**Comment by PharmCat** [comment]
re-run not help

```
Warning: GitHub returned a 5xx error code
```

**Comment by ericphanson** [comment]
BTW this issue is discussed a lot in https://github.com/JuliaRegistries/TagBot/issues/242 as well. But to summarize that issue, there's no known fix right now :(

**Comment by singularitti** [comment]
OK, I will close this.
