### ISSUE TITLE
Error after "Warning: No registry pull request was found for this version"

### ISSUE THREAD

**Issue by Jutho** [JuliaRegistries/TagBot#258]
After registering a new package ( https://github.com/Jutho/StridedViews.jl ) it seems TagBot is not able to create the tag, and the action prints out the following warning:
```
Warning: No registry pull request was found for this version
Error: TagBot experienced an unexpected internal failure
```
See  https://github.com/Jutho/StridedViews.jl/actions/runs/4260560015/jobs/7413862625#step:3:44

TagBot.yml file was created with the latest version of PkgTemplates.jl .

**Comment by RexWzh** [comment]
I get the same error just now.

**Comment by LudwigBoess** [comment]
I also get this error. I updated my TagBot workflow file to the latest version given in the README and also set up new SSH keys, just to be sure, but neither solved the problem

**Comment by junyuan-chen** [comment]
Same here. Does it only happen with new pacakges? Rerun the workflow doesn't help.

Here is the log:

```
Did not find registry PR
Processing version v0.1.0 (1fd3ed4e3d60f84cd96d0fce9d177949079a1e29)
Generating changelog for version v0.1.0 (1fd3ed4e3d60f84cd96d0fce9d177949079a1e29)
Warning: No registry pull request was found for this version
Creating release v0.1.0 at 1fd3ed4e3d60f84cd96d0fce9d177949079a1e29
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 94, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 5[45](https://github.com/junyuan-chen/NonlinearSystems.jl/actions/runs/4581529946/jobs/8091119101#step:3:46), in create_release
    self._repo.create_git_release(
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 1059, in create_git_release
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/releases/releases#create-a-release"}

Response (200): {
  "status": "Submitted error report"
}
```

**Comment by FedericoStra** [comment]
I get the same error trying to register a new version of an existing package:

- the commit: https://github.com/FedericoStra/ConservationLawsParticles.jl/commit/61985c67e696b68da47c226b1caebcd8e080ff9e
- the merged registration: https://github.com/JuliaRegistries/General/pull/84967
- the failing TagBot run: https://github.com/FedericoStra/ConservationLawsParticles.jl/actions/runs/5186972246/jobs/9348749127

The log:
```
Did not find registry PR
Processing version v0.8.3 (61985c67e696b68da47c226b1caebcd8e080ff9e)
Generating changelog for version v0.8.3 (61985c67e696b68da47c226b1caebcd8e080ff9e)
Warning: No registry pull request was found for this version
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 94, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line [53](https://github.com/FedericoStra/ConservationLawsParticles.jl/actions/runs/5186972246/jobs/9348749127#step:3:54)3, in create_release
    self._git.create_tag(version, sha, log)
  File "/root/tagbot/action/git.py", line 107, in create_tag
    self.command("push", "origin", version)
  File "/root/tagbot/action/git.py", line 71, in command
    raise Abort(f"Git command '{cmd}' failed")
tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_o779svb9 push origin v0.8.3' failed

Response (200): {
  "status": "Submitted error report"
}
```

**Comment by navidcy** [comment]
I get the same.... :( 
https://github.com/OceanBioME/OceanBioME.jl/actions/runs/5399088678/jobs/9805758047#step:3:43
