### ISSUE TITLE
TagBot run with error still succeeds

### ISSUE THREAD

**Issue by lgoettgens** [JuliaRegistries/TagBot#261]
I have seen multiple runs of TagBot (e.g. https://github.com/oscar-system/Oscar.jl/actions/runs/4697589698/jobs/8328833954), where there is an error in the execution. However, the CI job still succeeds. Wouldn't it be more sensible to mark it as failed so that users would notice it?

**Comment by fingolfin** [comment]
The error is about rate limiting. E.g. like this:
```
An unexpected, unreportable error occurred
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 49, in <module>
    repo = Repo(
  File "/root/tagbot/action/repo.py", line 72, in __init__
    self._registry = self._gh.get_repo(registry)
  File "/usr/local/lib/python3.8/site-packages/github/MainClass.py", line 345, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for installation ID 6710914.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

In our [TagBot.yml](https://github.com/oscar-system/Oscar.jl/blob/master/.github/workflows/TagBot.yml) we set `token: ${{ secrets.GITHUB_TOKEN }}` which i thought should be sufficient to avoid such rate limiting issues?
