### ISSUE TITLE
GithubException: 500 null

### ISSUE THREAD

**Issue by bjarthur** [JuliaRegistries/TagBot#308]
what does "GithubException: 500 null" indicate?  i thought it might mean the github servers were down, but the [status](https://www.githubstatus.com/) shows they're all green.

```
% docker run --rm ghcr.io/juliaregistries/tagbot python -m tagbot.local --repo GiovineItalia/Gadfly.jl --version v1.4.0 --token <SNIP>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/tagbot/local/__main__.py", line 70, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/tagbot/local/__main__.py", line 64, in main
    r.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 591, in create_release
    log = self._changelog.get(version_tag, sha)
  File "/root/tagbot/action/changelog.py", line 207, in get
    data = self._collect_data(version_tag, sha)
  File "/root/tagbot/action/changelog.py", line 190, in _collect_data
    "custom": self._custom_release_notes(version_tag),
  File "/root/tagbot/action/changelog.py", line 115, in _custom_release_notes
    pr = self._repo._registry_pr(package_version)
  File "/root/tagbot/action/repo.py", line 241, in _registry_pr
    for pr in prs:
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 201, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 398, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 423, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 500 null
```

**Comment by PeriHub** [comment]
I'm facing a similar problem: https://github.com/PeriHub/PeriLab.jl/actions/runs/8387463448/job/22969699204

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
