### ISSUE TITLE
Missing First Character of Sub-package Prefix

### ISSUE THREAD

**Issue by cadojo** [JuliaRegistries/TagBot#343]
I'm seeing what seems to be a new issue where the first character of the tag is missing, [seemingly](https://github.com/JuliaAstro/EphemerisSources.jl/actions/runs/10842866477/job/30089139875) due to the version string being sliced. I have not yet tried manually specifying the tag prefix. 

It's hard to say if this issue is new, I had a bad deploy token configuration which had caused TagBot to not work with this repository for some time now.

**Comment by tpoisot** [comment]
Same issue here -- the first letter of a version string that is `PkgName-v0.0.1` is interpreted as `kgName-v0.0.1` leading to no tag because it's invalid. This seems to be new-ish (as the exact same setup used to work a few weeks ago)

**Comment by tpoisot** [comment]
Here is the log, btw:

~~~
Processing version v1.0.0 (34d332b7e0205668ef8a8e8c80d2f312658a9bdb)
Generating changelog for version SimpleSDMLayers-v1.0.0 (34d332b7e0205668ef8a8e8c80d2f312658a9bdb)
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 96, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 595, in create_release
    log = self._changelog.get(version_tag, sha)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tagbot/action/changelog.py", line 225, in get
    data = self._collect_data(version_tag, sha)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tagbot/action/changelog.py", line 208, in _collect_data
    "backport": self._is_backport(version_tag),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tagbot/action/changelog.py", line 72, in _is_backport
    cur_ver = VersionInfo.parse(version[1:])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/semver/version.py", line 646, in parse
    raise ValueError(f"{version} is not valid SemVer string")
ValueError: impleSDMLayers-v1.0.0 is not valid SemVer string

Response (200): {
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 96, in <module>
  "status": "Submitted error report"
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 595, in create_release
}
    log = self._changelog.get(version_tag, sha)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tagbot/action/changelog.py", line 225, in get
    data = self._collect_data(version_tag, sha)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tagbot/action/changelog.py", line 208, in _collect_data
    "backport": self._is_backport(version_tag),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tagbot/action/changelog.py", line 72, in _is_backport
    cur_ver = VersionInfo.parse(version[1:])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/semver/version.py", line 646, in parse
    raise ValueError(f"{version} is not valid SemVer string")
ValueError: impleSDMLayers-v1.0.0 is not valid SemVer string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/tagbot/action/__main__.py", line 99, in <module>
    repo.handle_error(e)
  File "/root/tagbot/action/repo.py", line 641, in handle_error
    raise Abort("Cannot continue due to internal failure")
tagbot.action.Abort: Cannot continue due to internal failure
~~~

**Comment by tpoisot** [comment]
Looking at the trace + git blame, I think the issue is is: https://github.com/JuliaRegistries/TagBot/commit/7d86458e99522dc4d405542dd0b69f91b9691f12 (co-authored by @christopher-dG and @IanButterworth)

This is a commit from 3 weeks ago, and I had a tagbot run succeed for a subdir just before that. Looks like the `is_backport` function is not checking for the fact that the version string can be prefixed by a subdir name?

**Comment by IanButterworth** [comment]
Ah ok. If you have a fix in mind, please open a PR

**Comment by tpoisot** [comment]
I don't have a fix and I don't know the code base, sorry - as it's breaking a number of package releases (monorepos + subdirs are used by a few orgs now), do you think you will fix/revert this?

**Comment by IanButterworth** [comment]
Please take a look at https://github.com/JuliaRegistries/TagBot/pull/344

**Comment by tpoisot** [comment]
> Please take a look at #344

Amazing, thanks!

**Comment by IanButterworth** [comment]
v1.9.3 was just released with the fix. Please see if it works as expected.

**Comment by cadojo** [comment]
My CI works again, thank you!
